=== sonalikasamanta019-blip/V2V-Automation-Testing-Training-/external.dtd
<!ELEMENT allstudents (student*)>
<!ELEMENT student (name,email,contact,address*)>
<!ELEMENT name (#PCDATA|firstname|lastname)*>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT contact (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ATTLIST address type CDATA #REQUIRED>

=== sonalikasamanta019-blip/V2V-Automation-Testing-Training-/external1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE allstudents SYSTEM "external.dtd">
<allstudents>
<student>
<name>My name is<firstname>Sonalika</firstname><lastname>Samanta</lastname></name>
<email>sona@capgemini.com</email>
<contact>999999</contact>
<address type="office">pune</address>
</student>

<student>
<name>abhi</name>
<email>abhi@capgemini.com</email>
<contact>999999</contact>
<address type="office">pune</address>
<address type="home">pune</address>
</student>
</allstudents>
